name=Carberus
version=Beta test 1.0.0
author=rii66
maintainer=rii66
sentence=Global dual station core
paragraph=Original station module packaged as an Arduino library.
category=Device Control
architectures=c3 supermini android flash 
depends=PolluxS - CastorS - Config main 
